version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Entered the build phase...
  build:
    commands:
      - echo Entered the build phase...
      - mvn install
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/ttapp.jar
